apiVersion: apps/v1
kind: Deployment
metadata:
  name: padbot-mapper-go-zhw
spec:
  selector:
    matchLabels:
      app: padbot-mapper-go-zhw
  template:
    metadata:
      labels:
        app: padbot-mapper-go-zhw
    spec:
      restartPolicy: Always
      containers:
      - name: padbot-mapper-go-zhw
        image: huajuan6848/padbot_mapper_go:0.0.2
        volumeMounts:
        - name: config-volume
          mountPath: /opt/kubeedge
      nodeSelector:
        kubernetes.io/hostname: nuc-zhw
      volumes:
      - name: config-volume
        configMap:
          name: device-profile-config-nuc-zhw
---
apiVersion: v1
kind: Service
metadata:
  name: padbot-mapper-go-zhw
spec:
  type: NodePort
  selector:
    app: padbot-mapper-go-zhw
  ports:
  - nodePort: 31215
    port: 1215
    targetPort: 1215
